### ISSUE TITLE
Wrong Map.get usage

### ISSUE THREAD

**Issue by mike-kasianov** [ueberauth/ueberauth_github#18]
Just trying to visit /auth/github I see an exception `expected a map, got: [uid_field: :login, default_scope: "user,public_repo", oauth2_module: Ueberauth.Strategy.Github.OAuth]`

Looks like `Map.get` receives a keyword list as first argument instead of a Map.
`deps/ueberauth_github/lib/ueberauth/strategy/github.ex:214`
master branch

**Comment by doomspork** [comment]
@mike-kasianov would you like to open a PR to correct this?

**Comment by mike-kasianov** [comment]
@doomspork Just pushed the fix #19
