### ISSUE TITLE
Change :uid_field to :id instead of :login

### ISSUE THREAD

**Issue by mike-kasianov** [ueberauth/ueberauth_github#20]
Since user on github is free to change his login name it would be good to fix `deps/ueberauth_github/lib/ueberauth/strategy/github.ex:71` from `:login` to `:id`.

**Comment by doomspork** [comment]
@mike-kasianov I think this is a pretty fair assessment but this will be a breaking change.  @hassox / @scrogson any thoughts?

@mike-kasianov do you want to open a PR?

**Comment by mike-kasianov** [comment]
@doomspork sure #21

**Comment by mveytsman** [comment]
I think this issue should be closed since the PR #21 is merged.
