### ISSUE TITLE
conn.private.github_user not set in callback

### ISSUE THREAD

**Issue by naps62** [ueberauth/ueberauth_github#26]
Running a new phoenix 1.4 app, I'm having trouble accessing user data after sign in with Github

```elixir
plug Ueberauth

def callback(conn, %{"provider" => "github", "code" => code} = params) do
  IO.inspect conn.private.github_user # this is nil
end
```

However, editing the package's code directly in `deps/ueberauth_github`, and adding some `IO.inspect` calls, I'm able to verify that all the values are correctly set to the conn object there. They're just not being passed down.

Is there something I might be missing here?

**Comment by doomspork** [comment]
@naps62 is your code somewhere we could take a peek at?
