### ISSUE TITLE
warning: variable "client" does not exist and is being expanded to "client()

### ISSUE THREAD

**Issue by shahryarjb** [ueberauth/ueberauth_github#28]
hi after Compiled ( in terminal )
`
warning: variable "client" does not exist and is being expanded to "client()", please use parentheses to remove the ambiguity or change the variable name
  lib/ueberauth/strategy/github/oauth.ex:47
`

**Comment by doomspork** [comment]
Hi @shahryarjb!  A new version has been released that should address this for you 👍
