### ISSUE TITLE
client_id from configuration missing in Github request.

### ISSUE THREAD

**Issue by jmcervera** [ueberauth/ueberauth_github#33]
I really think I have all well configured, but I'm not getting the client id in the request for the github url. 

https://github.com/login/oauth/authorize?client_id=&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fauth%2Fgithub%2Fcallback&response_type=code&scope=user%2Cpublic_repo

**Comment by DarckBlezzer** [comment]
I have the same problem, I have all well configured, and the client_id is not passing in the URL, 
and I download the example and put mid client_id and secret_id and didn't work...

**Comment by doomspork** [comment]
Bugs need to include some information so we can properly debug.  This has been quiet for over a year.  Closing.
