### ISSUE TITLE
Provide hook to configure OAuth2 client because function Poison.decode!/1 is undefined

### ISSUE THREAD

**Issue by mildred** [ueberauth/ueberauth_github#50]
The issue has already been reported in #43. basically, the OAuth2 lib no longer depends on Poison as the JSON backend is now configurable. The only problem is that there is no hook to provide access to the OAuth2 client object to configure the JSON backend.

Would it be possible to provide such a hook?

perhaps updating the README to tell how it should be used might be nice too.

**Comment by tajchumber** [comment]
this is something similar to what we did in the `ueberauth_google` lib (https://github.com/ueberauth/ueberauth_google/pull/58)

I'll try to get it done shortly!
