### ISSUE TITLE
Latests version indicates 0.8.1 but hex.pm latest only has 0.8.0

### ISSUE THREAD

**Issue by raul-gracia** [ueberauth/ueberauth_github#64]
Looks like the latest version of the code has not been released to hex.pm.
`@version` specifies 0.8.1, which depends on `ueberauth ~> 0.7.0` but the latest version on hex.pm still has version `0.8.0` which depends on `ueberauth ~> 0.6.0`

Can you please upload the latest release to hex.pm ?

**Comment by raul-gracia** [comment]
@doomspork @robuye 👀

**Comment by raul-gracia** [comment]
Probably also worth re activating the Travis CI build, which was moved from `.org` domain to `.com` domain.
And also update the elixir and OTP target versions to include elixir `1.12` and OTP `24`

https://blog.travis-ci.com/2021-05-07-orgshutdown

**Comment by yordis** [comment]
let me get back to this, I need to setup GitHub Actions, hopefully today

**Comment by yordis** [comment]
@raul-gracia where `0.8.1` is specified? I can't find it

**Comment by raul-gracia** [comment]
@yordis Here: https://github.com/ueberauth/ueberauth_github/blob/master/mix.exs#L5

**Comment by yordis** [comment]
🤦🏻 I am stupid ... I was looking at an old version (didn't rebase)

**Comment by raul-gracia** [comment]
This is still in the same state as it was before... @yordis @doomspork @robuye

**Comment by yordis** [comment]
@raul-gracia yeah, the CI is fixed now, so let me do it, I am so sorry, too many things at once.
