### ISSUE TITLE
Cross-Site Request Forgery attack

### ISSUE THREAD

**Issue by tmkontra** [ueberauth/ueberauth_github#69]
### Steps to Reproduce

1. Install Ueberauth and Github strategy
```
{:ueberauth_github, "~> 0.8.1"},
{:ueberauth, "~> 0.7"},
```

(`:ueberauth` latest is 0.9, but `:ueberauth_github` is version-incompatible)

2. Ueberauth Config with Github provider:
```
config :ueberauth, Ueberauth,
  providers: [
    github: { Ueberauth.Strategy.Github, [default_scope: "user:email", allow_private_emails: true, send_redirect_uri: false] }
  ]
```

3. Github OAuth credentials from environment
```
config :ueberauth, Ueberauth.Strategy.Github.OAuth,
  client_id: env!("GITHUB_CLIENT_ID"),
  client_secret: env!("GITHUB_CLIENT_SECRET")
```

4. Configure :request and :callback routes

5. Attempt to Login with Github to http://localhost:4000/auth/github/callback

### Expected Result

Successful authentication and process a ueberauth_auth instance

### Actual Result

CSRF failure

```
%Ueberauth.Failure{errors: [%Ueberauth.Failure.Error{message: "Cross-Site Request Forgery attack", message_key: :csrf_attack}], provider: :github, strategy: Ueberauth.Strategy.Github}
```

More info:
It looks like by the time the Phoenix Error page is rendered for `GET /auth/github/callback`, the `ueberauth` cookie is no longer present. I am not sure if this is indicative of the cookie not being available when the `state` param comparison is executed.

EDIT:
It looks like the state cookie is indeed present, and appears to match the state query parameter. As far as I can tell, the CSRF protection mechanism should be satisfied:

<img width="1244" alt="Screen Shot 2022-06-01 at 11 33 08 PM" src="https://user-images.githubusercontent.com/46075030/171547698-24a04abc-ce10-43f0-a2f7-0325b8e35903.png">

**Comment by tmkontra** [comment]
Sorry, I am not sure what I changed, but it seems to be working now. No change to installed package versions, nor configs.

**Comment by bhelx** [comment]
I think this should be re-opened. Having the same issue. Here are my current dep versions:

```
      {:ueberauth, "0.10.3"},
      {:ueberauth_github, github: "ueberauth/ueberauth_github", branch: "master"},
```

Though i tried many iterations of this including downgrading everything.

@tmkontra Could you state what versions are in your `mix.lock` file?

**Comment by Darth-Knoppix** [comment]
Seeing the same issue with too with the same versions:

```
[
      {:ueberauth, "~> 0.10.3"},
      {:ueberauth_github, github: "ueberauth/ueberauth_github", tag: "v0.8.2"}
]
```

It looks like the cookie is present during the first request but not on the callback.

**Comment by meshbrainster** [comment]
Please reopen. Also seeing the exact same issue with the same versions as Darth-Knoppix

**Comment by bpar476** [comment]
I'm also having this issue with `:ueberauth, "~> 0.7"` and `:ueberauth_github, "~> 0.8"`. Tried in a normal tab and in an incognito tab. no luck.

**Comment by pepicrft** [comment]
For anyone coming across this issue, it seems to happen when the `Ueberauth` is added in the router and the auth controller. Because it runs twice, the router one deletes the state from the session and by the time the second one checks agains the session the value is not present. I'd recommend to keep it only in the controller.
