### ISSUE TITLE
0.8.2 isn't published to hex.pm

### ISSUE THREAD

**Issue by Darth-Knoppix** [ueberauth/ueberauth_github#74]
### Steps to Reproduce

Check https://hex.pm/packages/ueberauth_github for the latest published version or try adding the package to your mix.exs and running `mix deps.get`
```ex
[
  {:ueberauth_github, "~> 0.8.2"}
]
```

### Expected Result

The latest version is published and resolves correctly to 0.8.2

### Actual Result

`Because your app depends on ueberauth_github ~> 0.8.2 which doesn't match any versions, version solving failed.`

**Comment by Darth-Knoppix** [comment]
Using GitHub directly as workaround: `{:ueberauth_github, github: "ueberauth/ueberauth_github", tag: "v0.8.2"}`

**Comment by aiwaiwa** [comment]
This does seem to be resolved.
